services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=dockit'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
  dockit-server:
    build:
      dockerfile: ./Dockerfile
      tags:
        - "dockit-server"
    environment:
      - 'USERNAME=admin'
      - 'PASSWORD=changeit'
    ports:
      - '8080:8080'
